name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: litgpt
        environment-file: env.yml
        python-version: 3.12.2
        auto-activate-base: false
    - name: Install dependencies
      run: |
        echo "Listing installed packages"
        conda list
    - name: Activate Conda environment and Run tests
      shell: bash -l {0}
      run: |
        echo "Activating environment"
        conda activate litgpt
        echo "Running tests with pytest"
        pytest
