name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: litgpt
        environment-file: env.yml
        python-version: 3.12.2
        auto-activate-base: false
    - name: Install dependencies
      run: conda list
    - name: Run tests
      run: pytest
